apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  labels:
    app: hello
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: docker.io/jackyou2020/hello_flux:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000
