apiVersion: v1
kind: Service
metadata:
  name: hello
spec:
  type: NodePort
  ports:
    - name: hello
      port: 8000
      targetPort: 8000
      protocol: TCP
      NodePort: 30004
  selector:
    app: hello
